version: 2.1
orbs:
  node: circleci/node@6.3.0
jobs:
  build-test:
    executor:
      name: node/default
      tag: '22.14'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build the library
      - run:
          command: npm test
          name: Run tests
  lint:
    executor:
      name: node/default
      tag: '22.14'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run lint
          name: Run linting
workflows:
  build-test-lint:
    jobs:
      - build-test:
          filters:
            branches:
              ignore:
                - gh-pages
      - lint:
          filters:
            branches:
              ignore:
                - gh-pages
